language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - git config --global user.email "mail@bernhardrode.de"
  - git config --global user.name "Travis-CI"
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - node ./node_modules/grunt-cli/bin/grunt release
env:
  global:
    secure: { "lots-of-seemingly-random-characters" }
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
script:
  - "npm run test"
after_success:
  - "npm run deploy"
